/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * AuralHub — Audio / Aural learning mode.
 *
 * Uses Sarvam AI TTS (via backend) for high-quality narration when available.
 * Falls back to browser speech synthesis for free users or when Sarvam is unavailable.
 * Script is generated by Gemini as an engaging, student-friendly explanation.
 */

import React, { useState, useRef, useCallback, useEffect } from 'react';
import {
  Library, ClipboardCheck, RotateCcw, Download, Sparkles, Book,
  Mic, Play, Pause, Volume2, Lightbulb, Headphones,
  RefreshCw, ChevronDown, ChevronUp, ChevronLeft, ChevronRight,
  Loader2, AlertCircle, GraduationCap, Zap, BookOpen, Drama,
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { AIGuide } from '../common/AIGuide';

import { speak, stopSpeaking } from '../../lib/tts';
import { exportKitToPDF, setLastLearningMode } from '../../lib/pdfExport';
import { aiService } from '../../services/aiService';
import { UserStats, PlanType, PaywallConfig } from '../../types';

// ─── Types ──────────────────────────────────────────────────────────────────

type VoiceStyle = 'clear-teacher' | 'friendly-tutor' | 'exam-coach' | 'story-mode' | 'clear-narrator';
type AudioLanguage = 'en-IN' | 'hi-IN' | 'hinglish';

interface ScriptSections {
  // New structure (from updated prompt)
  hook?: string;
  mainExplanation?: string;
  example?: string;
  examTip?: string;
  recap?: string;
  challenge?: string;
  quickRecap?: string[];
  keyVocabulary?: { term: string; meaning: string; examUse: string }[];
  // Legacy fields (backward compat with cached kits)
  intro?: string;
  explanation?: string;
  quizCTA?: string;
}

interface AudioState {
  audioUrl: string | null;
  duration: string | null;
  script: string;
  scriptSections: ScriptSections | null;
  cached: boolean;
  sarvamUnavailable: boolean;
}

const VOICE_OPTIONS: { value: VoiceStyle; label: string; icon: React.ReactNode; desc: string; proPlan?: boolean }[] = [
  { value: 'clear-teacher', label: 'Class Teacher', icon: <GraduationCap size={16} />, desc: 'Calm, structured classroom style' },
  { value: 'friendly-tutor', label: 'Friendly Tutor', icon: <Headphones size={16} />, desc: 'Warm, conversational tone' },
  { value: 'exam-coach', label: 'Exam Coach', icon: <Zap size={16} />, desc: 'Marks-focused strategies' },
  { value: 'story-mode', label: 'Story Mode', icon: <Drama size={16} />, desc: 'Engaging concept stories', proPlan: true },
  { value: 'clear-narrator', label: 'Clear Narrator', icon: <Mic size={16} />, desc: 'Clean, simple summary' },
];

const LANGUAGE_OPTIONS: { value: AudioLanguage; label: string }[] = [
  { value: 'en-IN', label: 'English' },
  { value: 'hi-IN', label: 'Hindi' },
  { value: 'hinglish', label: 'Hinglish' },
];

const SPEED_OPTIONS = [1, 1.25, 1.5, 2];

// ─── Props ──────────────────────────────────────────────────────────────────

interface AuralHubProps {
  setView: (v: string) => void;
  onSave: (item: any) => void;
  kit?: any;
  stats: UserStats;
  planType?: PlanType;
  saveMistake: (mistake: { question: string; userAnswer: string; correction: string; mode: 'visual' | 'aural' | 'readwrite'; topic: string }) => void;
  openFlashcards?: (topic: string, sourceKitId?: string) => void;
  onPaywall?: (config: PaywallConfig) => void;
}

// ─── Component ──────────────────────────────────────────────────────────────

export const AuralHub = ({
  setView, onSave, kit, stats, planType = 'free',
  saveMistake, openFlashcards, onPaywall,
}: AuralHubProps) => {
  // ── No kit loaded guard ────────────────────────────────────────────────
  if (!kit) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] text-center px-6">
        <div className="w-16 h-16 rounded-2xl bg-indigo-100 flex items-center justify-center mb-4">
          <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-indigo-600"><path d="M12 9v4m0 4h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" /></svg>
        </div>
        <h3 className="text-lg font-bold text-on-surface mb-2">No content loaded</h3>
        <p className="text-sm text-on-surface-variant max-w-sm mb-6">Please select a chapter from the Library first. Audio content will be generated for the selected chapter.</p>
        <button onClick={() => setView('library')} className="px-6 py-3 bg-primary text-white rounded-xl font-bold text-sm hover:brightness-110">Go to Library</button>
      </div>
    );
  }

  // ── Data extraction ────────────────────────────────────────────────────
  const data = kit;

  const auralData = data.aural || { audioScript: '', lectureNotes: '' };
  const topicTitle = data.quiz?.title || data.title || data.topic || 'Topic';
  const subject = data.detectedSubject || data.subject || 'Science';
  const quiz = Array.isArray(data.quiz) ? data.quiz : (data.quiz?.questions || []);
  const isPlus = planType === 'plus' || planType === 'pro';
  const isPro = planType === 'pro';

  // ── State ──────────────────────────────────────────────────────────────
  const [voiceStyle, setVoiceStyle] = useState<VoiceStyle>('clear-teacher');
  const [language, setLanguage] = useState<AudioLanguage>('en-IN');
  const [speed, setSpeed] = useState(1);
  const [volume, setVolume] = useState(80);

  // Audio generation state
  const [isGenerating, setIsGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);
  const [audioState, setAudioState] = useState<AudioState | null>(null);

  // Playback state
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [audioDuration, setAudioDuration] = useState(0);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  // Browser TTS fallback state
  const [usingBrowserTTS, setUsingBrowserTTS] = useState(false);
  const [browserTTSProgress, setBrowserTTSProgress] = useState(0);

  // UI state
  const [expandedSection, setExpandedSection] = useState<string | null>(null);
  const [expandedScriptSection, setExpandedScriptSection] = useState<string | null>(null);
  const [vocabIndex, setVocabIndex] = useState(0);
  const [quizAnswers, setQuizAnswers] = useState<Record<number, string>>({});
  const [showQuizResults, setShowQuizResults] = useState(false);

  // Remember learning mode
  useEffect(() => { setLastLearningMode('aural'); }, []);

  // Clear stale audio when voice style or language changes
  const prevStyleRef = useRef(voiceStyle);
  const prevLangRef = useRef(language);
  useEffect(() => {
    if (prevStyleRef.current !== voiceStyle || prevLangRef.current !== language) {
      setAudioState(null);
      setIsPlaying(false);
      setVocabIndex(0);
      stopSpeaking();
      if (audioRef.current) { audioRef.current.pause(); audioRef.current.src = ''; }
      prevStyleRef.current = voiceStyle;
      prevLangRef.current = language;
    }
  }, [voiceStyle, language]);

  // ── Audio element setup ────────────────────────────────────────────────
  useEffect(() => {
    const audio = new Audio();
    audio.preload = 'auto';
    audioRef.current = audio;

    audio.addEventListener('timeupdate', () => {
      setCurrentTime(audio.currentTime);
    });
    audio.addEventListener('loadedmetadata', () => {
      setAudioDuration(audio.duration);
    });
    audio.addEventListener('ended', () => {
      setIsPlaying(false);
      setCurrentTime(0);
    });

    return () => {
      audio.pause();
      audio.src = '';
      stopSpeaking();
    };
  }, []);

  // Sync speed/volume to audio element
  useEffect(() => {
    if (audioRef.current) {
      audioRef.current.playbackRate = speed;
      audioRef.current.volume = volume / 100;
    }
  }, [speed, volume]);

  // ── Generate narration ─────────────────────────────────────────────────

  const handleGenerate = useCallback(async (regenerate = false) => {
    // Plan gate: free users can only read the script, no AI narration
    if (!isPlus && onPaywall) {
      onPaywall({
        title: 'AI Narration',
        description: 'AI-powered audio narration with Sarvam voices is available for Plus and Pro users. Upgrade to hear your chapters explained by an AI teacher.',
        ctaLabel: planType === 'free' ? 'Upgrade to Plus — ₹249/mo' : 'Upgrade to Exam Pro — ₹499/mo',
        requiredPlan: 'plus',
        benefits: [
          'AI-generated narration in multiple voices',
          'Hindi & Hinglish support',
          'Speed controls & transcript',
          'Exam Coach & Story Mode voices',
        ],
      });
      return;
    }

    // Story mode gate: Pro only
    if (voiceStyle === 'story-mode' && !isPro && onPaywall) {
      onPaywall({
        title: 'Story Mode Narration',
        description: 'Story Mode transforms textbook concepts into engaging narratives. Available exclusively for Exam Pro users.',
        ctaLabel: 'Upgrade to Exam Pro — ₹499/mo',
        requiredPlan: 'pro',
        benefits: [
          'Narrative storytelling for every chapter',
          'Longer chapter audio',
          'Downloadable MP3',
          'All voice styles unlocked',
        ],
      });
      return;
    }

    // Don't regenerate if we have cached audio (unless explicitly asked)
    if (!regenerate && audioState?.audioUrl && !audioState.sarvamUnavailable) return;

    setIsGenerating(true);
    setGenerateError(null);
    setIsPlaying(false);
    stopSpeaking();
    setUsingBrowserTTS(false);

    try {
      const result = await aiService.generateAudioNarration({
        topic: topicTitle,
        subject,
        classLevel: data.classLevel || 'Class 10',
        language,
        voiceStyle,
      });

      setAudioState({
        audioUrl: result.audioUrl,
        duration: result.duration,
        script: result.script,
        scriptSections: result.scriptSections,
        cached: result.cached,
        sarvamUnavailable: result.sarvamUnavailable,
      });

      // Load audio into the <audio> element
      if (result.audioUrl && audioRef.current) {
        audioRef.current.src = result.audioUrl;
        audioRef.current.load();
      }
    } catch (err: any) {
      setGenerateError(err.message || 'Failed to generate audio narration.');
    } finally {
      setIsGenerating(false);
    }
  }, [topicTitle, subject, data.classLevel, language, voiceStyle, isPlus, isPro, planType, onPaywall, audioState]);

  // ── Playback controls ──────────────────────────────────────────────────

  const togglePlayback = useCallback(() => {
    if (!audioState) return;

    // If we have Sarvam audio, use the <audio> element
    if (audioState.audioUrl && !audioState.sarvamUnavailable && audioRef.current) {
      if (isPlaying) {
        audioRef.current.pause();
        setIsPlaying(false);
      } else {
        audioRef.current.play().then(() => setIsPlaying(true)).catch(() => {});
      }
      return;
    }

    // Fallback: use browser speech synthesis
    if (isPlaying) {
      stopSpeaking();
      setIsPlaying(false);
      setUsingBrowserTTS(false);
      return;
    }

    const textToSpeak = audioState.script || auralData.audioScript || data.summary?.text || '';
    if (!textToSpeak) return;

    setUsingBrowserTTS(true);
    setIsPlaying(true);
    speak(
      textToSpeak,
      () => { setIsPlaying(false); setBrowserTTSProgress(0); setUsingBrowserTTS(false); },
      (p) => setBrowserTTSProgress(p),
      speed,
      volume / 100,
      0,
    );
  }, [audioState, isPlaying, speed, volume, auralData.audioScript, data.summary?.text]);

  const handleSeek = useCallback((e: React.MouseEvent<HTMLDivElement>) => {
    const rect = e.currentTarget.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const percent = Math.max(0, Math.min(1, x / rect.width));

    if (audioRef.current && audioState?.audioUrl && !audioState.sarvamUnavailable) {
      audioRef.current.currentTime = percent * audioDuration;
      setCurrentTime(audioRef.current.currentTime);
    }
  }, [audioDuration, audioState]);

  // ── Quiz handler ───────────────────────────────────────────────────────

  const handleQuizSubmit = () => {
    quiz.forEach((q: any, idx: number) => {
      const selected = quizAnswers[idx + 1];
      const correctVal = q.answer || q.correct;
      const isCorrect = selected === correctVal || selected?.startsWith(`${correctVal})`);
      if (!isCorrect && selected && !stats.mistakes.find(m => m.question === q.question)) {
        saveMistake({
          question: q.question,
          userAnswer: selected || 'Not answered',
          correction: `Correct Answer: ${correctVal}. ${q.explanation || ''}`,
          mode: 'aural',
          topic: topicTitle,
        });
      }
    });
    setShowQuizResults(true);
  };

  // ── Helpers ────────────────────────────────────────────────────────────

  const formatTime = (seconds: number) => {
    const m = Math.floor(seconds / 60);
    const s = Math.floor(seconds % 60);
    return `${m}:${s.toString().padStart(2, '0')}`;
  };

  const progress = audioState?.audioUrl && !audioState.sarvamUnavailable && audioDuration > 0
    ? (currentTime / audioDuration) * 100
    : usingBrowserTTS ? browserTTSProgress : 0;

  const hasAudio = audioState?.audioUrl && !audioState.sarvamUnavailable;
  const hasScript = audioState?.script || auralData.audioScript;

  // ─── Render ────────────────────────────────────────────────────────────

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="space-y-8"
    >
      {/* ── Header ─────────────────────────────────────────────────────── */}
      <div className="space-y-5">
        <div>
          <span className="inline-block px-3 py-1 rounded bg-indigo-100 text-[10px] font-bold mb-3 uppercase tracking-widest text-indigo-600 border border-indigo-200">
            Aural Hub
          </span>
          <h2 className="text-3xl font-bold tracking-tight text-on-surface">
            {topicTitle}
          </h2>
          <p className="text-on-surface-variant text-sm mt-1">
            Audio learning workspace {'·'} {subject} {'·'} {data.classLevel || 'Class 10'}{data.stream ? ` · ${data.stream}` : ''}
          </p>
        </div>

        {/* Action buttons */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
          <button
            onClick={() => onSave({
              title: topicTitle,
              type: 'aural',
              contentSnippet: (audioState?.script || auralData.audioScript || '').substring(0, 120),
              tags: [
                `voice:${voiceStyle}`,
                `lang:${language}`,
                ...(audioState?.duration ? [`duration:${audioState.duration}`] : []),
                ...(subject ? [`subject:${subject}`] : []),
              ],
            })}
            className="h-11 flex items-center justify-center gap-2 bg-indigo-100 text-indigo-700 px-4 rounded-lg shadow-sm hover:bg-indigo-200 transition-all font-bold text-sm"
          >
            <Library size={16} />
            Save to Library
          </button>
          <button
            onClick={() => setView('practice')}
            className="h-11 flex items-center justify-center gap-2 bg-navy-dark text-white px-4 rounded-lg shadow-sm hover:bg-indigo-600 transition-all font-bold text-sm"
          >
            <ClipboardCheck size={16} />
            Take Hub Quiz
          </button>
          <button
            onClick={() => openFlashcards?.(topicTitle, kit?.id)}
            className="h-11 flex items-center justify-center gap-2 bg-indigo-600 text-white px-4 rounded-lg shadow-sm hover:brightness-110 transition-all font-bold text-xs leading-tight text-center"
          >
            <Sparkles size={16} className="shrink-0" />
            <span>Key Term Flashcards</span>
          </button>
          <button
            onClick={() => setView('dashboard')}
            className="h-11 flex items-center justify-center gap-2 bg-white border border-surface-container-high text-on-surface px-4 rounded-lg shadow-sm hover:bg-surface-container-low transition-all font-bold text-sm"
          >
            <RotateCcw size={16} />
            Reset
          </button>
          <button
            onClick={() => exportKitToPDF(kit, 'aural')}
            className="h-11 flex items-center justify-center gap-2 bg-primary text-white px-4 rounded-lg shadow-md hover:opacity-90 active:scale-95 transition-all font-bold text-sm"
          >
            <Download size={16} />
            Download PDF
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* ── Left column: Player + Transcript ──────────────────────── */}
        <div className="lg:col-span-8 flex flex-col gap-6">

          {/* ── Audio Player Card ─────────────────────────────────── */}
          <div className="bg-white border border-surface-container-high rounded-2xl overflow-hidden card-shadow">
            {/* Cover / Player header */}
            <div className="relative bg-gradient-to-br from-indigo-900 via-indigo-800 to-purple-900 p-8 pb-6">
              <div className="flex items-start justify-between">
                <div>
                  <p className="text-xs font-bold text-indigo-300 uppercase tracking-[0.2em] mb-2">
                    {hasAudio ? 'AI Narration Ready' : audioState?.sarvamUnavailable ? 'Script Ready' : 'Audio Learning'}
                  </p>
                  <h3 className="text-2xl font-bold text-white mb-1 leading-tight">
                    {topicTitle}
                  </h3>
                  <p className="text-indigo-300 text-sm">
                    {VOICE_OPTIONS.find(v => v.value === voiceStyle)?.label || 'Clear Teacher'} {'·'} {LANGUAGE_OPTIONS.find(l => l.value === language)?.label || 'English'}
                    {audioState?.duration && ` · ${audioState.duration}`}
                  </p>
                </div>
                <div className="w-16 h-16 rounded-full bg-white/10 backdrop-blur-md border border-white/20 flex items-center justify-center">
                  <Headphones size={32} className="text-white" />
                </div>
              </div>

              {/* Waveform visualiser */}
              <div className="flex items-end justify-center gap-[3px] h-10 mt-6">
                {[...Array(40)].map((_, i) => (
                  <motion.div
                    key={i}
                    animate={{ height: isPlaying ? [6, Math.random() * 36 + 6, 6] : 6 }}
                    transition={{ repeat: Infinity, duration: 0.4 + Math.random() * 0.4, ease: 'easeInOut' }}
                    className={`w-[3px] rounded-full ${isPlaying ? 'bg-indigo-300' : 'bg-indigo-700'}`}
                  />
                ))}
              </div>

              {/* Progress bar */}
              <div className="mt-4 space-y-1">
                <div
                  className="h-1.5 w-full bg-white/10 rounded-full overflow-hidden cursor-pointer group"
                  onClick={handleSeek}
                >
                  <motion.div
                    className="h-full bg-indigo-400 relative rounded-full"
                    animate={{ width: `${progress}%` }}
                    transition={{ type: 'spring', bounce: 0, duration: 0.2 }}
                  >
                    <div className="absolute right-0 top-1/2 -translate-y-1/2 w-3 h-3 bg-white rounded-full shadow opacity-0 group-hover:opacity-100 transition-opacity" />
                  </motion.div>
                </div>
                <div className="flex justify-between text-[10px] font-mono text-indigo-400">
                  <span>{hasAudio ? formatTime(currentTime) : usingBrowserTTS ? `${Math.floor(browserTTSProgress)}%` : '0:00'}</span>
                  <span>{hasAudio ? formatTime(audioDuration) : audioState?.duration || '--:--'}</span>
                </div>
              </div>

              {/* Playback controls */}
              <div className="flex items-center justify-center gap-6 mt-4">
                <button
                  onClick={togglePlayback}
                  disabled={!audioState && !auralData.audioScript}
                  className="w-16 h-16 rounded-full bg-white text-indigo-900 flex items-center justify-center shadow-lg hover:scale-105 active:scale-95 transition-all disabled:opacity-40 disabled:cursor-not-allowed"
                >
                  {isPlaying ? <Pause size={28} fill="currentColor" /> : <Play size={28} fill="currentColor" className="ml-1" />}
                </button>
              </div>

              {/* Speed + Volume */}
              <div className="flex flex-col sm:flex-row items-center justify-between gap-4 mt-6 pt-4 border-t border-white/10">
                <div className="flex items-center gap-3 w-full sm:w-auto">
                  <Volume2 size={16} className="text-indigo-400 shrink-0" />
                  <input
                    type="range"
                    min="0"
                    max="100"
                    value={volume}
                    onChange={(e) => setVolume(Number(e.target.value))}
                    className="w-28 h-1 bg-white/10 rounded-lg appearance-none cursor-pointer accent-indigo-400"
                  />
                  <span className="text-[10px] font-mono text-indigo-400 w-8">{volume}%</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-[10px] font-bold text-indigo-400 uppercase tracking-widest mr-1">Speed</span>
                  <div className="flex bg-white/10 rounded p-0.5">
                    {SPEED_OPTIONS.map(opt => (
                      <button
                        key={opt}
                        onClick={() => setSpeed(opt)}
                        className={`px-3 py-1 text-[10px] font-bold rounded transition-colors ${speed === opt ? 'bg-indigo-500 text-white shadow-sm' : 'text-indigo-300 hover:bg-white/10'}`}
                      >
                        {opt}x
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* ── Voice & Language selectors ─────────────────────── */}
            <div className="p-6 border-t border-surface-container space-y-4">
              {/* Voice style */}
              <div>
                <p className="text-[10px] font-bold uppercase tracking-widest text-on-surface-variant mb-2">Voice Style</p>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                  {VOICE_OPTIONS.map(v => (
                    <button
                      key={v.value}
                      onClick={() => {
                        if (v.proPlan && !isPro && onPaywall) {
                          onPaywall({
                            title: 'Story Mode',
                            description: 'Story Mode narration is an Exam Pro exclusive.',
                            ctaLabel: 'Upgrade to Exam Pro — ₹499/mo',
                            requiredPlan: 'pro',
                          });
                          return;
                        }
                        setVoiceStyle(v.value);
                      }}
                      className={`relative flex items-center gap-2 px-3 py-2.5 rounded-lg text-xs font-bold transition-all border ${
                        voiceStyle === v.value
                          ? 'bg-indigo-50 border-indigo-300 text-indigo-700 shadow-sm'
                          : 'bg-white border-surface-container-high text-on-surface-variant hover:border-indigo-200'
                      }`}
                    >
                      {v.icon}
                      <div className="text-left">
                        <span className="block">{v.label}</span>
                        <span className="block text-[9px] font-medium opacity-70">{v.desc}</span>
                      </div>
                      {v.proPlan && !isPro && (
                        <span className="absolute -top-1.5 -right-1.5 px-1 py-0.5 bg-amber-500 text-white text-[7px] font-black rounded uppercase">Pro</span>
                      )}
                    </button>
                  ))}
                </div>
              </div>

              {/* Language */}
              <div className="flex items-center gap-4">
                <p className="text-[10px] font-bold uppercase tracking-widest text-on-surface-variant">Language</p>
                <div className="flex bg-surface-container rounded p-0.5">
                  {LANGUAGE_OPTIONS.map(l => (
                    <button
                      key={l.value}
                      onClick={() => setLanguage(l.value)}
                      className={`px-4 py-1.5 text-xs font-bold rounded transition-colors ${language === l.value ? 'bg-indigo-600 text-white shadow-sm' : 'text-on-surface-variant hover:bg-white/80'}`}
                    >
                      {l.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Generate button */}
              <div className="flex items-center gap-3">
                <button
                  onClick={() => handleGenerate(false)}
                  disabled={isGenerating}
                  className="flex-1 h-12 flex items-center justify-center gap-2 bg-indigo-600 text-white px-6 rounded-xl shadow-md hover:bg-indigo-700 active:scale-[0.98] transition-all font-bold text-sm disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {isGenerating ? (
                    <>
                      <Loader2 size={18} className="animate-spin" />
                      Generating Narration...
                    </>
                  ) : audioState ? (
                    <>
                      <RefreshCw size={16} />
                      Regenerate Narration
                    </>
                  ) : (
                    <>
                      <Mic size={16} />
                      Generate Narration
                    </>
                  )}
                </button>
                {audioState && (
                  <button
                    onClick={() => handleGenerate(true)}
                    disabled={isGenerating}
                    className="h-12 px-4 flex items-center justify-center gap-2 bg-white border border-surface-container-high text-on-surface-variant rounded-xl hover:bg-surface-container-low transition-all font-bold text-xs disabled:opacity-50"
                    title="Regenerate with different settings"
                  >
                    <RefreshCw size={14} />
                    New
                  </button>
                )}
              </div>

              {/* Error message */}
              {generateError && (
                <div className="flex items-start gap-2 p-3 bg-red-50 border border-red-200 rounded-lg">
                  <AlertCircle size={16} className="text-red-500 shrink-0 mt-0.5" />
                  <p className="text-xs text-red-700 font-medium">{generateError}</p>
                </div>
              )}

              {/* Sarvam unavailable notice */}
              {audioState?.sarvamUnavailable && (
                <div className="flex items-start gap-2 p-3 bg-amber-50 border border-amber-200 rounded-lg">
                  <AlertCircle size={16} className="text-amber-600 shrink-0 mt-0.5" />
                  <div>
                    <p className="text-xs text-amber-800 font-bold">Audio generation unavailable</p>
                    <p className="text-[11px] text-amber-700 mt-0.5">
                      You can still read the explanation script below, or use browser narration (play button).
                    </p>
                  </div>
                </div>
              )}

              {/* Cached notice */}
              {audioState?.cached && !audioState.sarvamUnavailable && (
                <p className="text-[10px] text-on-surface-variant">
                  <Sparkles size={10} className="inline mr-1" />
                  Using cached audio. Click <strong>New</strong> to regenerate with fresh settings.
                </p>
              )}
            </div>
          </div>

          {/* ── Quick Recap ─────────────────────────────────────────── */}
          {(() => {
            const qr = audioState?.scriptSections?.quickRecap;
            const fallbackPts = Array.isArray(data.summary?.keyPoints) ? data.summary.keyPoints.slice(0, 7) : null;
            const points = (Array.isArray(qr) && qr.length > 0) ? qr : fallbackPts;
            if (!points || points.length === 0) return null;
            return (
              <div className="bg-white border border-surface-container-high rounded-2xl p-6 card-shadow">
                <div className="flex items-center gap-2 mb-4">
                  <div className="p-1.5 bg-emerald-50 rounded-lg text-emerald-600">
                    <RefreshCw size={16} />
                  </div>
                  <h3 className="text-base font-black text-on-surface">Quick Recap</h3>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {points.map((pt: string, i: number) => (
                    <div key={i} className="flex items-start gap-2.5 p-3 bg-emerald-50 border border-emerald-100 rounded-xl">
                      <span className="mt-1 w-5 h-5 rounded-full bg-emerald-500 text-white flex items-center justify-center text-[10px] font-black shrink-0">{i + 1}</span>
                      <p className="text-sm font-medium text-on-surface leading-snug">{pt}</p>
                    </div>
                  ))}
                </div>
              </div>
            );
          })()}

          {/* ── View Full Script (collapsed by default) ───────────── */}
          {(audioState?.scriptSections || audioState?.script || auralData.audioScript) && (
            <div className="bg-white border border-surface-container-high rounded-2xl card-shadow overflow-hidden">
              <button
                onClick={() => setExpandedSection(expandedSection === 'transcript' ? null : 'transcript')}
                className="w-full flex items-center justify-between p-5 text-left hover:bg-indigo-50/30 transition-colors"
              >
                <div className="flex items-center gap-2">
                  <BookOpen size={16} className="text-indigo-600" />
                  <span className="text-sm font-bold text-on-surface">View Full Script</span>
                  {audioState?.duration && (
                    <span className="text-[10px] font-bold text-on-surface-variant bg-surface-container px-2 py-0.5 rounded-full">{audioState.duration}</span>
                  )}
                </div>
                {expandedSection === 'transcript' ? <ChevronUp size={16} className="text-on-surface-variant" /> : <ChevronDown size={16} className="text-on-surface-variant" />}
              </button>
              <AnimatePresence>
                {expandedSection === 'transcript' && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.25 }}
                    className="overflow-hidden"
                  >
                    <div className="px-5 pb-5 space-y-3">
                      {/* Accordion sections */}
                      {audioState?.scriptSections && ([
                        { key: 'hook', altKey: 'intro', label: 'Hook', icon: <Sparkles size={14} />, cls: 'indigo' },
                        { key: 'mainExplanation', altKey: 'explanation', label: 'Main Explanation', icon: <Book size={14} />, cls: 'blue' },
                        { key: 'example', altKey: '', label: 'Real-Life Example', icon: <Lightbulb size={14} />, cls: 'amber' },
                        { key: 'examTip', altKey: '', label: 'Exam Tip', icon: <Zap size={14} />, cls: 'red' },
                        { key: 'recap', altKey: '', label: 'Recap', icon: <RefreshCw size={14} />, cls: 'green' },
                        { key: 'challenge', altKey: 'quizCTA', label: 'Challenge', icon: <ClipboardCheck size={14} />, cls: 'purple' },
                      ] as { key: string; altKey: string; label: string; icon: React.ReactNode; cls: string }[]).map(section => {
                        const ss = audioState.scriptSections!;
                        const content = (ss as any)[section.key] || (section.altKey ? (ss as any)[section.altKey] : null);
                        if (!content || typeof content !== 'string') return null;
                        const isOpen = expandedScriptSection === section.key;
                        return (
                          <div key={section.key} className={`border rounded-xl overflow-hidden border-${section.cls}-200`}>
                            <button
                              onClick={(e) => { e.stopPropagation(); setExpandedScriptSection(isOpen ? null : section.key); }}
                              className={`w-full flex items-center justify-between p-3.5 text-left hover:bg-${section.cls}-50/50 transition-colors`}
                            >
                              <div className="flex items-center gap-2">
                                <span className={`text-${section.cls}-600`}>{section.icon}</span>
                                <span className="text-xs font-bold text-on-surface">{section.label}</span>
                              </div>
                              {isOpen ? <ChevronUp size={14} className="text-on-surface-variant" /> : <ChevronDown size={14} className="text-on-surface-variant" />}
                            </button>
                            <AnimatePresence>
                              {isOpen && (
                                <motion.div
                                  initial={{ height: 0, opacity: 0 }}
                                  animate={{ height: 'auto', opacity: 1 }}
                                  exit={{ height: 0, opacity: 0 }}
                                  transition={{ duration: 0.2 }}
                                  className="overflow-hidden"
                                >
                                  <div className="px-3.5 pb-3.5">
                                    <p className="text-sm text-on-surface leading-relaxed whitespace-pre-wrap">{content}</p>
                                  </div>
                                </motion.div>
                              )}
                            </AnimatePresence>
                          </div>
                        );
                      })}
                      {/* Full flowing script */}
                      {(audioState?.script || auralData.audioScript) && (
                        <div className="pt-3 border-t border-surface-container">
                          <button
                            onClick={(e) => { e.stopPropagation(); setExpandedScriptSection(expandedScriptSection === 'full' ? null : 'full'); }}
                            className="text-xs font-bold text-indigo-600 hover:text-indigo-800 transition-colors"
                          >
                            {expandedScriptSection === 'full' ? 'Hide Full Flowing Script' : 'Show Full Flowing Script'}
                          </button>
                          <AnimatePresence>
                            {expandedScriptSection === 'full' && (
                              <motion.div
                                initial={{ height: 0, opacity: 0 }}
                                animate={{ height: 'auto', opacity: 1 }}
                                exit={{ height: 0, opacity: 0 }}
                                className="overflow-hidden"
                              >
                                <p className="text-sm text-on-surface leading-relaxed mt-3 whitespace-pre-wrap bg-surface-container-low p-4 rounded-lg max-h-96 overflow-y-auto">
                                  {audioState?.script || auralData.audioScript}
                                </p>
                              </motion.div>
                            )}
                          </AnimatePresence>
                        </div>
                      )}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          )}
        </div>

        {/* ── Right column: Tips → Vocabulary Carousel → Formula Sheet → Plan ── */}
        <div className="lg:col-span-4 space-y-6">
          {/* 1. Tips & Suggestions (AIGuide) */}
          <AIGuide topic={topicTitle} customTips={data.readWrite?.tips} />

          {/* 2. Key Vocabulary — carousel/slideshow */}
          {(() => {
            const kv = audioState?.scriptSections?.keyVocabulary;
            const fallbackKv = Array.isArray(data.summary?.keyVocabulary) ? data.summary.keyVocabulary.map((v: any) => ({
              term: typeof v === 'string' ? v : (v.term || v.word || ''),
              meaning: typeof v === 'string' ? '' : (v.definition || v.meaning || ''),
              examUse: '',
            })) : null;
            const vocab = (Array.isArray(kv) && kv.length > 0) ? kv : fallbackKv;
            if (!vocab || vocab.length === 0) return null;
            const safeIndex = Math.min(vocabIndex, vocab.length - 1);
            const current = vocab[safeIndex];
            return (
              <div className="bg-white border border-surface-container-high rounded-2xl p-5 card-shadow">
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center gap-2">
                    <div className="p-1.5 bg-violet-50 rounded-lg text-violet-600">
                      <BookOpen size={16} />
                    </div>
                    <h3 className="text-sm font-black text-on-surface">Key Vocabulary</h3>
                  </div>
                  <span className="text-[10px] font-bold text-on-surface-variant bg-surface-container px-2 py-0.5 rounded-full">
                    {safeIndex + 1} / {vocab.length}
                  </span>
                </div>
                <AnimatePresence mode="wait">
                  <motion.div
                    key={safeIndex}
                    initial={{ opacity: 0, x: 30 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -30 }}
                    transition={{ duration: 0.2 }}
                    className="border border-violet-100 rounded-xl p-4 bg-violet-50/50 min-h-[100px]"
                  >
                    <p className="text-base font-black text-violet-800 mb-1.5">{current.term}</p>
                    {current.meaning && <p className="text-xs text-on-surface font-medium leading-relaxed mb-2">{current.meaning}</p>}
                    {current.examUse && (
                      <p className="text-[10px] text-violet-600 font-bold flex items-start gap-1">
                        <Zap size={10} className="shrink-0 mt-0.5" />
                        {current.examUse}
                      </p>
                    )}
                  </motion.div>
                </AnimatePresence>
                <div className="flex items-center justify-between mt-3">
                  <button
                    onClick={() => setVocabIndex(safeIndex <= 0 ? vocab.length - 1 : safeIndex - 1)}
                    className="w-9 h-9 rounded-full border border-violet-200 bg-violet-50 text-violet-600 flex items-center justify-center hover:bg-violet-100 transition-colors"
                  >
                    <ChevronLeft size={18} />
                  </button>
                  <div className="flex gap-1.5">
                    {vocab.map((_: any, i: number) => (
                      <button
                        key={i}
                        onClick={() => setVocabIndex(i)}
                        className={`w-2 h-2 rounded-full transition-all ${i === safeIndex ? 'bg-violet-500 scale-125' : 'bg-violet-200 hover:bg-violet-300'}`}
                      />
                    ))}
                  </div>
                  <button
                    onClick={() => setVocabIndex(safeIndex >= vocab.length - 1 ? 0 : safeIndex + 1)}
                    className="w-9 h-9 rounded-full border border-violet-200 bg-violet-50 text-violet-600 flex items-center justify-center hover:bg-violet-100 transition-colors"
                  >
                    <ChevronRight size={18} />
                  </button>
                </div>
              </div>
            );
          })()}

          {/* 3. Formula Sheet / Quick Reference */}
          {(() => {
            const formulas = data.formulaTable || [];
            const defs = Array.isArray(data.definitions) ? data.definitions : (data.summary?.definitions || []);
            if (formulas.length === 0 && defs.length === 0) return null;
            return (
              <div className="bg-white border border-surface-container-high rounded-2xl p-5 card-shadow">
                <div className="flex items-center gap-2 mb-3">
                  <div className="p-1.5 bg-emerald-50 rounded-lg text-emerald-600">
                    <Lightbulb size={16} />
                  </div>
                  <h3 className="text-sm font-black text-on-surface">
                    {formulas.length > 0 ? 'Formula Sheet' : 'Quick Reference'}
                  </h3>
                </div>
                <div className="space-y-2 max-h-[300px] overflow-y-auto">
                  {formulas.length > 0 ? (
                    formulas.map((row: any, i: number) => (
                      <div key={i} className="p-2.5 bg-emerald-50 rounded-lg border border-emerald-100">
                        <p className="text-xs font-bold text-emerald-800">{row.name}</p>
                        <p className="text-[11px] text-emerald-700 font-mono font-semibold mt-0.5">{row.formula}</p>
                        {row.notes && <p className="text-[10px] text-emerald-600 mt-0.5">{row.notes}</p>}
                      </div>
                    ))
                  ) : (
                    defs.slice(0, 8).map((d: any, i: number) => (
                      <div key={i} className="p-2.5 bg-blue-50 rounded-lg border border-blue-100">
                        <p className="text-xs font-bold text-blue-800">{d.word || d.term || 'Term'}</p>
                        <p className="text-[10px] text-blue-700 mt-0.5">{d.definition || d.meaning || d.def || ''}</p>
                      </div>
                    ))
                  )}
                </div>
              </div>
            );
          })()}

          {/* Download Audio (shown separately if available) */}
          {isPro && hasAudio && (
            <a
              href={audioState?.audioUrl || '#'}
              download={`${topicTitle.replace(/\s+/g, '-').toLowerCase()}-narration.wav`}
              className="flex items-center gap-3 p-4 rounded-2xl bg-amber-50 border border-amber-200 hover:bg-amber-100 transition-colors text-left card-shadow"
            >
              <Download size={18} className="text-amber-600 shrink-0" />
              <div>
                <p className="text-sm font-bold text-on-surface">Download Audio</p>
                <p className="text-[10px] text-on-surface-variant">Save for offline listening</p>
              </div>
            </a>
          )}

          {/* 4. Plan badge */}
          <div className={`p-4 rounded-xl border text-center ${
            isPro ? 'bg-amber-50 border-amber-200' : isPlus ? 'bg-indigo-50 border-indigo-200' : 'bg-surface-container-low border-surface-container-high'
          }`}>
            <p className="text-[10px] font-bold uppercase tracking-widest text-on-surface-variant mb-1">Audio Mode</p>
            <p className={`text-sm font-black ${isPro ? 'text-amber-700' : isPlus ? 'text-indigo-700' : 'text-on-surface-variant'}`}>
              {isPro ? 'Exam Pro — All Voices Unlocked' : isPlus ? 'Plus — AI Narration Active' : 'Free — Browser Speech Only'}
            </p>
            {!isPlus && (
              <button
                onClick={() => onPaywall?.({
                  title: 'Unlock AI Narration',
                  description: 'Get high-quality AI voices, Hindi support, and downloadable audio.',
                  ctaLabel: 'Upgrade to Plus — ₹249/mo',
                  requiredPlan: 'plus',
                })}
                className="mt-2 text-xs font-bold text-indigo-600 hover:underline"
              >
                Upgrade for AI Voices
              </button>
            )}
          </div>
        </div>
      </div>
    </motion.div>
  );
};
